services:
  - type: web
    name: femicide-analyzer
    env: docker
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: |
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_NAME
        value: "Femicide Analyzer"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://femicide-analyzer-yder.onrender.com"
      - key: LOG_CHANNEL
        value: "stack"
      - key: LOG_LEVEL
        value: "debug"
      # Database config (from Render's internal URL)
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        value: "dpg-d2k2gkn5r7bs73eb05ng-a"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "femicide_db"
      - key: DB_USERNAME
        value: "femicide_db_user"
      - key: DB_PASSWORD
        value: "8Pgy8xTChUJRE0mXibm9PUOE3kvc7ayx"
    postDeployCommand: |
      php artisan migrate --force
