services:
  - type: web
    name: femicide-analyzer
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://femicide-analyzer.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: femicide-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: femicide-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: femicide-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: femicide-db
          property: password

databases:
  - name: femicide-db
    plan: free
